### ISSUE TITLE
In the Town.mod is a cover of Rob Hubbard's Highscore music for the c64 port of Commando

### ISSUE THREAD

**Issue by Farbs** [DeerTears/GB-Studio-Community-Assets#34]
[Original tune](https://www.youtube.com/watch?v=hLp8ErRj8s0)

Should it be included here under an MIT license if the original is still under copyright?

**Comment by DeerTears** [comment]
Oh jeez, thank you for spotting that. It should not be in this repo if the original is in fact still under copyright.
